default_flags = "g"
capture_mouse = false

[[verbs]]
key = "ctrl-l"
internal = ":panel_right_no_open"

[[verbs]]
key = "ctrl-backspace"
internal = ":panel_left_no_open"

[[verbs]]
key = "ctrl-w"
internal = ":input_del_word_left"

[[verbs]]
invocation = "edit"
shortcut = "e"
external = "$EDITOR +{line} {file}"
leave_broot = false
