#!/bin/sh

sxhkd ~/.config/sxhkd/sxhkdrc_bspwm &
feh --bg-scale --no-xinerama $WALLPAPER &

for m in $(bspc query --monitors --names); do
    bspc monitor $m -d 1 2 3 4 5 6 7 8 9 10
done

bspc config border_width        1
bspc config window_gap          0

bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
