name: check
on:
  workflow_dispatch:
  push:
    paths:
      - "src/"
      - "flake.lock"
      - "flake.nix"
      - ".sops.yml"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "src/"
      - "flake.lock"
      - "flake.nix"
      - ".sops.yml"
      - ".github/workflows/build.yml"

jobs:
  check:
    strategy:
      matrix:
        # macos-14 is aarch64-darwin (silicone)
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # install nix
      - uses: DeterminateSystems/nix-installer-action@main
      # cache packages
      - uses: DeterminateSystems/magic-nix-cache-action@main
      # info on flake dependencies
      - uses: DeterminateSystems/flake-checker-action@main
        env:
          FLAKE_CHECKER_NO_TELEMETRY: true
        # validate all outputs
      - name: Validate flake outputs
        run: nix flake check
