name: check
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**/*.nix"
      - "flake.lock"
      - "flake.nix"
      - ".sops.yml"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "src/**/*.nix"
      - "flake.lock"
      - "flake.nix"
      - ".sops.yml"
      - ".github/workflows/build.yml"

jobs:
  check:
    strategy:
      # always run all platforms disregarding failure
      fail-fast: false
      matrix:
        # macos-14 is aarch64-darwin (silicon)
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # install nix
      - uses: DeterminateSystems/nix-installer-action@main
      # # cache packages
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      # info on flake dependencies
      - uses: DeterminateSystems/flake-checker-action@main
        env:
          FLAKE_CHECKER_NO_TELEMETRY: true
        # validate all outputs
      - name: Validate flake outputs
        # Building uses too much storage (more than available on GitHub runners) and passing --not-build
        # causes a lot of errors. So, for now comment out the home-manager derivations in the flake checks
        # and only test system configs. Not sure what else can be done besides somehow fixing all the
        # upstream errors caused by packages when passing --no-build.
        run: nix flake check --show-trace
